- group: { name: future, enabled: true }
- group: { name: extra, enabled: true }
- group: { name: use-lens, enabled: true }
- group: { name: use-th-quotes, enabled: true }
- group: { name: generalise, enabled: true }
- group: { name: generalise-for-conciseness, enabled: true }
- group: { name: teaching, enabled: true }
