name: Continuous Integration
on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: "9.6"
          cabal-version: "3.12"
      - run: just generate-cache-key
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: cabal-plan-${{ hashFiles('**/plan.json') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: just build-dependencies
      - uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - run: just build
      - run: just test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          path: .
          fail-on: warning
