name: ci
on: [push, pull_request]

jobs:
  ci:
    name: Build, lint and test
    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: haskell-actions/setup@v2
        id: setup
        # with:
        # ghc-version: ${{ matrix.ghc-version }}
        # Defaults, added for clarity:
        # cabal-version: "latest"
        # cabal-update: true

      - name: Generate cache key
        run: cabal build --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: cabal-plan-${{ hashFiles('**/plan.json') }}
          # restore-keys: ${{ env.key }}-

      - name: Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
        if: steps.cache.outputs.cache-hit != 'true'
        run: cabal build all --only-dependencies

      - name: Save cached dependencies
        uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all

      - name: Check cabal file
        run: cabal check
